#!/bin/sh
find src integration-tests \
	-path integration-tests/node_modules -prune -false -o \( \
	-type f \
	-name "*.java" \
	-o -name "*.html" \
	-o -name "*.css" \
	-o -name "*.js" \
	-o -name "*.peb" \
	\) -exec cat {} \; | grep -vE "^\\s*\$" | wc -l
	#\)
